# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-28 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bug_description', models.TextField(blank=True)),
                ('steps_to_replicate', models.TextField(blank=True)),
                ('actual_output', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('date_reported', models.DateTimeField(blank=True, null=True)),
                ('bug_type', models.CharField(choices=[('UI', 'User Interface'), ('functional', 'Functional'), ('recurring', 'Recurring')], default='functional', max_length=15)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='tracker.Project')),
            ],
        ),
    ]
