# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-19 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_bug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ending Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='production_site',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Production URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='staging_site',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Staging URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Starting Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_of_project',
            field=models.CharField(choices=[('Kanban', 'Kanban'), ('Scrum', 'Scrum')], default='Scrum', max_length=10, verbose_name='Type of Project'),
        ),
    ]
