# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-20 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_project_rename_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='project_name',
            new_name='project',
        ),
    ]
