# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-20 02:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0007_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tester',
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(through='tracker.Team', to=settings.AUTH_USER_MODEL),
        ),
    ]
