# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-20 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_project_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamMember',
        ),
    ]
