# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-20 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0010_fix_slug_population'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='Team',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_members',
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(through='tracker.Team', to=settings.AUTH_USER_MODEL),
        ),
    ]
