# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-23 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_fix_rename_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_severity', models.CharField(choices=[('Blocker', 'Blocker'), ('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor'), ('Trivial', 'Trivial'), ('Enhancement', 'Enhancement')], default='Critical', max_length=20)),
                ('bug_priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Critical', max_length=20)),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('for_testing', 'For Testing'), ('test_in_progress', 'Testing in Progress'), ('has_issues', 'Still has issues'), ('done', 'Done'), ('on_dev', 'On Dev')], default='For Testing', max_length=50)),
                ('device', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('na', 'Not Applicable')], default='na', max_length=10)),
                ('browser', models.CharField(choices=[('firefox', 'Firefox'), ('chrome', 'Chrome'), ('others', 'Others'), ('na', 'Not Applicable')], default='na', max_length=10)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Bug')),
            ],
        ),
    ]
